version: '3.9'
services:
  echo-postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: echo-postgresql
      POSTGRES_USER: echo-postgresql
      POSTGRES_PASSWORD: echo-postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - echo-postgresql:/var/lib/postgresql/data/
volumes:
  echo-postgresql:
